services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b-backend-app
    network_mode: host
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      EXTERNAL_API: ${EXTERNAL_API}
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    restart: unless-stopped