spring.application.name=b-backend
spring.mongodb.uri=${MONGODB_URI}
app.jwt.secret=${JWT_SECRET}
app.ext.url=${EXTERNAL_API}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}